name: Java CI

on: [push]

jobs:

  build-java11:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk+fx
    - name: Install External Tools
      run: | 
            sudo apt-get update && sudo apt install \
            libmsiecf-utils=20181227-1.1 \
            pff-tools=20180714-2 \
            libesedb-utils=20181229-3.1 \
            tesseract-ocr=4.1.1-2build2 \
            tesseract-ocr-por=1:4.00~git30-7274cfa-1 \
            imagemagick=8:6.9.10.23+dfsg-2.1ubuntu11.4 gsfonts
            sudo perl -MCPAN -e 'install Parse::Win32Registry'
    - name: Compile libagdb
      # libagdb (agdbinfo) needs to be built from source
      if: steps.libagdb.outputs.cache-hit != 'true'
      run: | 
            sudo apt install git autoconf automake autopoint libtool pkg-config
            git clone https://github.com/FelipeFcosta/libagdb.git
            cd libagdb/ && sudo ./synclibs.sh && sudo ./autogen.sh
            sudo ./configure
    - name: Install external parsers tools
      run: |
          cd libagdb/ && sudo make install
          sudo ldconfig
          cd ..
          sudo apt-get install libscca-utils rifiuti2 libevtx-utils libevt-utils

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - shell: bash
      run:
        cd target && mv release iped-snapshot-$GITHUB_SHA && tar -zcvf ../iped-snapshot.tar.gz iped-snapshot-$GITHUB_SHA
    - name: Upload snapshot
      uses: actions/upload-artifact@v1
      with:
        name: iped-snapshot-${{ github.sha }}
        path: iped-snapshot.tar.gz

  build-java14:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: curl -O "https://download.bell-sw.com/java/14.0.2+13/bellsoft-jdk14.0.2+13-linux-amd64-full.tar.gz"
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        jdkFile: ./bellsoft-jdk14.0.2+13-linux-amd64-full.tar.gz

    - name: Install External Tools
      run: | 
            sudo apt-get update && sudo apt install \
            libmsiecf-utils=20181227-1.1 \
            pff-tools=20180714-2 \
            libesedb-utils=20181229-3.1 \
            tesseract-ocr=4.1.1-2build2 \
            tesseract-ocr-por=1:4.00~git30-7274cfa-1 \
            imagemagick=8:6.9.10.23+dfsg-2.1ubuntu11.4 gsfonts
            sudo perl -MCPAN -e 'install Parse::Win32Registry'
    - name: Compile libagdb
      # libagdb (agdbinfo) needs to be built from source
      if: steps.libagdb.outputs.cache-hit != 'true'
      run: | 
            sudo apt install git autoconf automake autopoint libtool pkg-config
            git clone https://github.com/libyal/libagdb.git
            cd libagdb/ && sudo ./synclibs.sh && sudo ./autogen.sh
            sudo ./configure
    - name: Install external parsers tools
      run: |
          cd libagdb/ && sudo make install
          sudo ldconfig
          cd ..
          sudo apt-get install libscca-utils rifiuti2 libevtx-utils libevt-utils
    - name: Build with Maven
      run: mvn -B package --file pom.xml
