name: Java CI

on: [push]

jobs:
  build-java8:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk+fx
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - shell: bash
      run:
        cd target && mv release iped-snapshot-$GITHUB_SHA && tar -zcvf ../iped-snapshot.tar.gz iped-snapshot-$GITHUB_SHA
    - name: Upload snapshot
      uses: actions/upload-artifact@v1
      with:
        name: iped-snapshot-${{ github.sha }}
        path: iped-snapshot.tar.gz

  build-java11:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk+fx
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  build-java14:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: curl -O "https://download.bell-sw.com/java/14.0.2+13/bellsoft-jdk14.0.2+13-linux-amd64-full.tar.gz"
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        jdkFile: ./bellsoft-jdk14.0.2+13-linux-amd64-full.tar.gz
    - name: Build with Maven
      run: mvn -B package --file pom.xml
